// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqwaHfcWV6wbXzmi1ILDQ5OcraCs_5QvU',
    appId: '1:536182795648:web:950d126bdb4f520e6aa565',
    messagingSenderId: '536182795648',
    projectId: 'appproject-af4e2',
    authDomain: 'appproject-af4e2.firebaseapp.com',
    storageBucket: 'appproject-af4e2.appspot.com',
    measurementId: 'G-E6ZGHEG79B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJd_ixtF-pLqUyyG_IfKgW92QWtmnZJyc',
    appId: '1:536182795648:android:19761bc47fc6252f6aa565',
    messagingSenderId: '536182795648',
    projectId: 'appproject-af4e2',
    storageBucket: 'appproject-af4e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvgYoJNjnWfLX_b8vkDxZhHfLNf-jLzM',
    appId: '1:536182795648:ios:d085381c700308066aa565',
    messagingSenderId: '536182795648',
    projectId: 'appproject-af4e2',
    storageBucket: 'appproject-af4e2.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvgYoJNjnWfLX_b8vkDxZhHfLNf-jLzM',
    appId: '1:536182795648:ios:d085381c700308066aa565',
    messagingSenderId: '536182795648',
    projectId: 'appproject-af4e2',
    storageBucket: 'appproject-af4e2.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqwaHfcWV6wbXzmi1ILDQ5OcraCs_5QvU',
    appId: '1:536182795648:web:69e4f886ee68275c6aa565',
    messagingSenderId: '536182795648',
    projectId: 'appproject-af4e2',
    authDomain: 'appproject-af4e2.firebaseapp.com',
    storageBucket: 'appproject-af4e2.appspot.com',
    measurementId: 'G-1L3NNGF3N7',
  );

}